spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/checkpointdb
    username: root
    password: c620918fazuKl420
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
redis:
  database: Giulia-free-db
  password: password
  host: redis-host
  port: 10990
